apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-ride-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-ride-api-app
  template:
    metadata:
      labels:
        app: the-ride-api-app
    spec:
      containers:
        - name: the-ride-api-image
          image: the-ride-api:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: the-ride-config