apiVersion: apps/v1
kind: Deployment
metadata:
  name: TheRideDeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: TheRideApiImage
          image: TheRideApi:latest
          envFrom:
            - configMapRef:
                name: TheRideConfig