apiVersion: v1
kind: Service
metadata:
  name: TheRideService
spec:
  type: NodePort
  selector:
    app: my-app # Selects the Pods running your application.
  ports:
    - name: http
      port: 80 # The port on which the service is exposed inside the cluster.
      targetPort: 8080 # The port on which your application is listening.
      nodePort: 30080 # The port on which the service is exposed on each node.