apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-init-script
  namespace: the-ride-ns
data:
  init-script.sh: |
    #!/bin/bash
    cqlsh -e "CREATE KEYSPACE IF NOT EXISTS the_ride WITH replication = {'class' : 'SimpleStrategy', 'replication_factor' : 1};"
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: the-ride-ns
spec:
  selector:
    app: cassandra
  ports:
    - name: cql
      port: 9042
      targetPort: 9042
    - name: jmx
      port: 7199
      targetPort: 7199
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: the-ride-ns
spec:
  serviceName: cassandra
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: bitnami/cassandra:latest
          env:
            - name: CASSANDRA_KEYSPACE_NAME
              value: the_ride
            - name: CASSANDRA_AUTHENTICATION
              value: false
            - name: CASSANDRA_KEYSPACE_REPLICATION_FACTOR
              value: "1"
          ports:
            - name: cql
              containerPort: 9042
            - name: jmx
              containerPort: 7199
          volumeMounts:
            - name: data
              mountPath: /bitnami/cassandra/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: cassandra-data
        - name: init-script
          configMap:
            name: cassandra-init-script
