apiVersion: v1
kind: Service
metadata:
  name: the-ride-cassandra
  namespace: the-ride-ns
spec:
  clusterIP: None
  selector:
    app: cassandra
  ports:
    - name: cql
      port: 9042
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: the-ride-ns
spec:
  serviceName: cassandra
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: bitnami/cassandra:latest
          env:
            - name: CASSANDRA_USER
              valueFrom:
                configMapKeyRef:
                  name: the-ride-config
                  key: db_username
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: the-ride-secret
                  key: db_password
            - name: CASSANDRA_DATACENTER
              valueFrom:
                configMapKeyRef:
                  name: the-ride-config
                  key: db_local-datacenter
          volumeMounts:
            - name: data-volume
              mountPath: /bitnami/cassandra/data/
      volumes:
        - name: data-volume
          hostPath:
            path: /Users/okoedion-aikhomu/DevCenter/PersonalDevCenter/DB_VOLUMES/the_ride/
